new

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -30,16 +30,8 @@ jobs:
 
       - name: Update ASG desired capacity
         run: |
-          if aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names example-asg; then
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg --desired-capacity 1
-          else
-            echo "ASG example-asg not found"
-          fi
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg --desired-capacity 1 || echo "ASG example-asg not found"
 
       - name: Update ASG2 desired capacity
         run: |
-          if aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names example-asg2; then
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg2 --desired-capacity 1
-          else
-            echo "ASG example-asg2 not found"
-          fi
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg2 --desired-capacity 1 || echo "ASG example-asg2 not found"
